source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/completion.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/keys/fzf.vim
source $HOME/.config/nvim/keys/nerdtree.vim
source $HOME/.config/nvim/lsp/languages.vim
source $HOME/.config/nvim/keys/lsp.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/themes/onedark.vim
